name: thesis_env

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.12
  - mne
  - scipy
  - pandas
  - matplotlib
  - scikit-learn
  - shap
  - pyriemann
  - openpyxl
  - ipykernel      # Aanbevolen: Jupyter Notebooks
  # - xlrd         # Alleen aanzetten als je écht oude .xls files moet inlezen