"""
=============================================================================
8. GENERATE ALL OVERLEAF TABLES (LATEX FORMATTER)
=============================================================================
Overview:
    This overarching script finds all the key CSV results generated by both 
    the SVM and Riemannian pipelines (Band Selection, Bias, Test Set, and 
    Cross-Domain) and converts them into publication-ready LaTeX tables.
    
    Output is a single .txt file ready to be copy-pasted directly into Overleaf.

Execution:
    python 8_Generate_All_Latex_Tables.py
=============================================================================
"""

import pandas as pd
from pathlib import Path
import sys

current_dir = Path(__file__).resolve().parent
sys.path.append(str(current_dir.parent))
from config import SVM_DATA_DIR, RIEMANN_DATA_DIR

def generate_latex():
    print("🚀 STARTING STEP 8: GENERATING MASTER LATEX TABLES")
    
    latex_content = "% =============================================================================\n"
    latex_content += "% MASTER LATEX TABLES FOR THESIS (COPY-PASTE INTO OVERLEAF)\n"
    latex_content += "% Requires: \\usepackage{booktabs} and \\usepackage{graphicx} in preamble.\n"
    latex_content += "% =============================================================================\n\n"

    # =========================================================================
    # TABLE 1: RIEMANNIAN BAND SELECTION SCOREBOARD
    # =========================================================================
    band_csv = RIEMANN_DATA_DIR / "riemann_band_selection_scoreboard.csv"
    if band_csv.exists():
        df_band = pd.read_csv(band_csv)
        latex_content += "% --- TABLE: Riemannian Band Selection ---\n"
        latex_content += "\\begin{table}[htbp]\n"
        latex_content += "    \\centering\n"
        latex_content += "    \\caption{Riemannian Band Selection & Architecture Optimization (Internal CV)}\n"
        latex_content += "    \\label{tab:riemann_band_selection}\n"
        latex_content += "    \\begin{tabular}{llc}\n"
        latex_content += "        \\toprule\n"
        latex_content += "        \\textbf{Frequency Band} & \\textbf{Architecture} & \\textbf{Balanced Accuracy} \\\\\n"
        latex_content += "        \\midrule\n"
        
        for _, row in df_band.iterrows():
            latex_content += f"        {row['Band']} & {row['Architecture']} & {row['CV_Balanced_Accuracy']:.3f} \\\\\n"
            
        latex_content += "        \\bottomrule\n"
        latex_content += "    \\end{tabular}\n"
        latex_content += "\\end{table}\n\n"
        print(" -> Table generated: Riemannian Band Selection")

    # =========================================================================
    # TABLE 2: COMBINED ALGORITHMIC BIAS REPORT (SVM vs RIEMANN)
    # =========================================================================
    bias_csv = SVM_DATA_DIR / "combined_algorithmic_bias_report.csv"
    if bias_csv.exists():
        df_bias = pd.read_csv(bias_csv)
        latex_content += "% --- TABLE: Combined Demographic Bias ---\n"
        latex_content += "\\begin{table}[htbp]\n"
        latex_content += "    \\centering\n"
        latex_content += "    \\caption{Algorithmic Bias Check: SVM vs Riemannian Test Accuracy by Demographic Group}\n"
        latex_content += "    \\label{tab:demographic_bias}\n"
        latex_content += "    \\begin{tabular}{llccc}\n"
        latex_content += "        \\toprule\n"
        latex_content += "        \\textbf{Category} & \\textbf{Subgroup} & \\textbf{N Segments} & \\textbf{SVM Acc.} & \\textbf{Riemann Acc.} \\\\\n"
        latex_content += "        \\midrule\n"
        
        current_cat = ""
        for _, row in df_bias.iterrows():
            # Only print category name if it changes (for visual cleanliness)
            cat_display = row['Category'] if row['Category'] != current_cat else ""
            current_cat = row['Category']
            
            latex_content += f"        {cat_display} & {row['Group']} & {row['N_Segments']} & {row['SVM_Accuracy']:.3f} & {row['Riemann_Accuracy']:.3f} \\\\\n"
            
        latex_content += "        \\bottomrule\n"
        latex_content += "    \\end{tabular}\n"
        latex_content += "\\end{table}\n\n"
        print(" -> Table generated: Combined Algorithmic Bias")

    # =========================================================================
    # TABLE 3: RIEMANNIAN TEST SET RESULTS (CLINICAL METRICS)
    # =========================================================================
    test_csv = RIEMANN_DATA_DIR / "riemann_testset_results.csv"
    if test_csv.exists():
        df_test = pd.read_csv(test_csv)
        latex_content += "% --- TABLE: Final Clinical Metrics ---\n"
        latex_content += "\\begin{table}[htbp]\n"
        latex_content += "    \\centering\n"
        latex_content += "    \\caption{Riemannian Classification Performance on Unseen Test Set}\n"
        latex_content += "    \\label{tab:riemann_testset_metrics}\n"
        latex_content += "    \\resizebox{\\textwidth}{!}{%\n"
        latex_content += "    \\begin{tabular}{llcccccccc}\n"
        latex_content += "        \\toprule\n"
        latex_content += "        \\textbf{Layout} & \\textbf{Band} & \\textbf{Bal. Acc.} & \\textbf{AUPRC} & \\textbf{AUROC} & \\textbf{Sens.} & \\textbf{Prec.} & \\textbf{Brier} & \\textbf{ECE} \\\\\n"
        latex_content += "        \\midrule\n"
        
        for _, row in df_test.iterrows():
            layout = "Whole-Brain" if row['Layout'] == 'whole' else "Central ROI"
            latex_content += f"        {layout} & {row['Band'].capitalize()} & "
            latex_content += f"{row['Bal_Acc']:.3f} & {row['AUPRC']:.3f} & {row['ROC_AUC']:.3f} & "
            latex_content += f"{row['Sensitivity']:.3f} & {row['Precision']:.3f} & "
            latex_content += f"{row['Brier_Score']:.3f} & {row['ECE']:.3f} \\\\\n"
            
        latex_content += "        \\bottomrule\n"
        latex_content += "    \\end{tabular}%\n"
        latex_content += "    }\n"
        latex_content += "\\end{table}\n\n"
        print(" -> Table generated: Final Clinical Metrics")

    # =========================================================================
    # TABLE 4: RIEMANNIAN CROSS DOMAIN (TRADABOOST)
    # =========================================================================
    # Zoek naar het Cross Domain CSV bestand (dynamische bestandsnaam afhankelijk van de band)
    cross_domain_files = list(RIEMANN_DATA_DIR.glob("Table_1_Riemann_cross_domain_*.csv"))
    if cross_domain_files:
        df_cross = pd.read_csv(cross_domain_files[-1]) # Pak de meest recente
        latex_content += "% --- TABLE: Riemannian Cross-Domain TrAdaBoost ---\n"
        latex_content += "\\begin{table}[htbp]\n"
        latex_content += "    \\centering\n"
        latex_content += "    \\caption{Cross-Domain Validation (TrAdaBoost vs Direct Training) on NCCP Target Set}\n"
        latex_content += "    \\label{tab:riemann_cross_domain}\n"
        latex_content += "    \\begin{tabular}{lccc}\n"
        latex_content += "        \\toprule\n"
        latex_content += "        \\textbf{Total CV Folds} & \\textbf{Avg Training Subjects} & \\textbf{Transfer Learning Score} & \\textbf{Direct Training Score} \\\\\n"
        latex_content += "        \\midrule\n"
        
        for _, row in df_cross.iterrows():
            latex_content += f"        {int(row['Total_Folds'])} & {row['Avg_Train_Subjects']:.1f} & {row['Transfer_Learning']:.3f} & {row['Direct_Training']:.3f} \\\\\n"
            
        latex_content += "        \\bottomrule\n"
        latex_content += "    \\end{tabular}\n"
        latex_content += "\\end{table}\n\n"
        print(" -> Table generated: Riemannian Cross-Domain (TrAdaBoost)")

    # =========================================================================
    # EXPORT THE COMPILED FILE
    # =========================================================================
    output_path = current_dir / "All_Thesis_Overleaf_Tables.txt"
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(latex_content)
        
    print(f"\n✅ All Overleaf tables successfully exported to: src/{output_path.name}")

if __name__ == "__main__":
    generate_latex()