"""
=============================================================================
2. FINAL EXTERNAL VALIDATION (Testing on Unseen Data)
=============================================================================
Overview:
    This script performs the final, unbiased evaluation of the trained models.
    It acts as an external validation step, strictly isolating the test data.
    
    For EACH band, it will:
        1. Open the isolated 20% test dataset (the "vault").
        2. Load the frozen model artifacts (.pkl) generated by the training script.
        3. Apply the exact same feature subset and mathematical scaling to 
           the unseen data to prevent any data leakage.
        4. Predict the diagnosis (Healthy Control vs. Fibromyalgia Patient).
        5. Calculate the true performance metrics (Accuracy, ROC-AUC, Precision, Recall).
        6. Generate and save the final Confusion Matrix plots for your thesis.

Execution:
    python test_unseen_data.py
=============================================================================
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path
import sys
import joblib

from sklearn.metrics import accuracy_score, precision_score, recall_score, roc_auc_score, confusion_matrix

current_dir = Path(__file__).resolve().parent
sys.path.append(str(current_dir.parent))
from config import RESULTS_DIR

print("🔓 Opening the Vault: Loading Unseen Test Data...")
test_path = RESULTS_DIR / "final_dataset_test.csv"
test_df = pd.read_csv(test_path)

y_test = test_df['Target'].values
meta_cols = ['Subject', 'Target', 'Condition', 'Segment']
X_test_full = test_df.drop(columns=[c for c in meta_cols if c in test_df.columns])

bands = ['delta', 'theta', 'alpha', 'beta', 'gamma'] 
test_results = []

print(f"\n📊 Evaluating models on unseen data...")

for band in bands:
    model_path = RESULTS_DIR / f"saved_model_{band}.pkl"
    
    if not model_path.exists():
        print(f"⚠️ Model for {band} not found. Skipping...")
        continue
        
    # 1. LOAD THE FROZEN ARTIFACTS
    artifact = joblib.load(model_path)
    final_svm = artifact['model']
    scaler = artifact['scaler']
    roi_features = artifact['roi_features']
    selected_features = artifact['selected_features']
    
    # 2. PREPARE THE TEST DATA EXACTLY AS IN TRAINING
    X_test_roi = X_test_full[roi_features]
    X_test_scaled = pd.DataFrame(scaler.transform(X_test_roi), columns=roi_features)
    X_test_final = X_test_scaled[selected_features]
    
    # 3. PREDICT
    y_pred = final_svm.predict(X_test_final)
    y_prob = final_svm.predict_proba(X_test_final)[:, 1]
    
    # 4. CALCULATE TRUE METRICS
    acc = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred, zero_division=0)
    rec = recall_score(y_test, y_pred, zero_division=0)
    auc = roc_auc_score(y_test, y_prob)
    
    test_results.append({
        'Band': band.upper(),
        'Unseen_Accuracy': acc,
        'ROC_AUC': auc,
        'Precision': prec,
        'Recall': rec
    })
    
    # 5. GENERATE CONFUSION MATRIX
    cm = confusion_matrix(y_test, y_pred)
    plt.figure(figsize=(6, 5))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', 
                xticklabels=['Healthy (0)', 'Fibro (1)'], 
                yticklabels=['Healthy (0)', 'Fibro (1)'],
                annot_kws={"size": 16})
    plt.title(f'{band.upper()} Band FINAL Validation\n(Accuracy: {acc:.2%})', fontsize=14)
    plt.ylabel('True Label', fontsize=12)
    plt.xlabel('Predicted Label', fontsize=12)
    plt.tight_layout()

    plot_path = RESULTS_DIR / f"final_confusion_matrix_{band}.png"
    plt.savefig(plot_path, dpi=300)
    plt.close()

# --- SUMMARY REPORT ---
print("\n" + "*"*80)
print("🏆 FINAL TRUE PERFORMANCE ON UNSEEN TEST DATA")
print("*"*80)
summary_df = pd.DataFrame(test_results).sort_values(by='Unseen_Accuracy', ascending=False)
print(summary_df.to_string(index=False))

summary_path = RESULTS_DIR / "final_test_results.csv"
summary_df.to_csv(summary_path, index=False)
print(f"\n💾 Validation results saved to: {summary_path}")